# golangci-lint configuration
# Reference: https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  # Preserve go version from go.mod
  go: ""
  # Modules download mode for go modules
  modules-download-mode: readonly
  # Allow parallel runners
  allow-parallel-runners: true

output:
  # Sort results by file, line, and column
  sort-results: true

linters:
  # Disable all linters first, then enable specific ones
  disable-all: true
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Report suspicious constructs
    - ineffassign   # Detect unused variable assignments
    - staticcheck   # Static analysis checks
    - unused        # Find unused code

    # Additional recommended linters
    - bodyclose     # Check HTTP response body is closed
    - contextcheck  # Check context.Context is passed correctly
    - durationcheck # Check for two durations multiplied together
    - errname       # Check error naming conventions
    - errorlint     # Find issues with error wrapping
    - copyloopvar   # Check for pointers to loop variables (Go 1.22+)
    - gocritic      # Opinionated linter with many checks
    - gofmt         # Check code formatting
    - gosec         # Security checks
    - misspell      # Find commonly misspelled words
    - nilerr        # Find returning nil after checking error
    - noctx         # Find HTTP requests without context
    - predeclared   # Find shadowed predeclared identifiers
    - revive        # Fast, configurable linter (golint replacement)
    - unconvert     # Remove unnecessary type conversions
    - wastedassign  # Find wasted assignment statements

linters-settings:
  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check blank identifier assignments
    check-blank: false
    # Exclude some functions from checking
    exclude-functions:
      - io.Copy
      - io.WriterTo.WriteTo
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteByte
      - (*bytes.Buffer).WriteString
      - (*strings.Builder).Write
      - (*strings.Builder).WriteByte
      - (*strings.Builder).WriteString

  gocritic:
    # Enable all stable checks
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam        # Allow passing large structs by value
      - rangeValCopy     # Allow range value copy for clarity
      - appendCombine    # Allow separate appends for readability
      - ifElseChain      # Allow if-else chains when clearer
      - assignOp         # Allow explicit assignment for clarity

  gofmt:
    # Simplify code
    simplify: true

  goimports:
    # Put local imports after 3rd party
    local-prefixes: github.com/garyellow/ntpu-linebot-go

  gosec:
    # Exclude certain rules
    excludes:
      - G104  # Audit errors not checked (handled by errcheck)
      - G115  # Integer overflow conversion (false positive for LINE API params)
      - G304  # File path from variable (we validate paths)
      - G401  # Use of weak cryptographic primitive (we only use for jitter)
      - G501  # Import blocklist: crypto/md5 (not used)

  misspell:
    locale: US

  revive:
    # Revive rules configuration
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true  # Allow unexported comments
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
        disabled: true  # Allow packages without comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  staticcheck:
    # Enable all checks
    checks: ["all"]

  unparam:
    # Check exported functions
    check-exported: false

issues:
  # Maximum issues count per linter
  max-issues-per-linter: 50
  # Maximum same issues count
  max-same-issues: 10
  # Exclude some issues in test files
  exclude-rules:
    # Ignore certain linters in test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
        - errorlint
    # Ignore long lines in generated files
    - path: ".*_generated\\.go"
      linters:
        - lll
    # Scraper client: caller is responsible for closing response body
    - path: internal/scraper/client\.go
      linters:
        - bodyclose
    # Warmup: context.Background() is intentionally used for background goroutine
    - path: internal/warmup/warmup\.go
      linters:
        - contextcheck
  # Include default excludes
  include:
    - EXC0012  # exported (.+) should have comment
    - EXC0014  # comment on exported (.+) should be of the form

severity:
  # Default severity for issues
  default-severity: warning
  # Rules for specific severities
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error
