# golangci-lint v2 configuration
# Reference: https://golangci-lint.run/docs/configuration/
# Migration guide: https://golangci-lint.run/docs/product/migration-guide/

version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
  go: '1.25'

linters:
  # v2: Use 'default' instead of 'disable-all'
  default: none
  enable:
    # Essential linters (must have)
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect unused variable assignments
    - staticcheck   # Static analysis (merged gosimple, stylecheck in v2)
    - unused        # Find unused code

    # Security and reliability
    - bodyclose     # Check HTTP response body is closed
    - contextcheck  # Check context.Context is passed correctly
    - fatcontext    # Detect nested contexts in structs (performance issue)
    - gosec         # Security checks
    - noctx         # Find HTTP requests without context
    - sqlclosecheck # Check SQL rows/statements are closed

    # Code quality and style
    - copyloopvar   # Check for pointers to loop variables (Go 1.22+)
    - durationcheck # Check for two durations multiplied together
    - errname       # Check error naming conventions
    - errorlint     # Find issues with error wrapping
    - gocritic      # Opinionated linter with many checks
    - mirror        # Reports wrong mirror patterns of bytes/strings usage
    - misspell      # Find commonly misspelled words
    - nilerr        # Find returning nil after checking error
    - predeclared   # Find shadowed predeclared identifiers
    - reassign      # Checks that package variables are not reassigned
    - revive        # Fast, configurable linter (golint replacement)
    - unconvert     # Remove unnecessary type conversions
    - wastedassign  # Find wasted assignment statements
    - whitespace    # Check for unnecessary whitespace

    # Performance
    - perfsprint    # Optimize fmt.Sprintf into faster alternatives
    - prealloc      # Find slice declarations that could be preallocated

    # Logging and observability
    - sloglint      # Ensure consistent code style with log/slog
    - spancheck     # Checks for mistakes with OpenTelemetry/Census spans

    # Additional useful linters
    - intrange      # Check integer range loop patterns (Go 1.22+)
    - errchkjson    # Check json.Marshal errors
    - forcetypeassert # Require type assertion checks
    - makezero      # Check slice initialization
    - nilnil        # Disallow simultaneous nil returns
    - protogetter   # Reports direct reads from proto message fields
    - testifylint   # Testify best practices
    - thelper       # Test helper detection
    - unparam       # Detect unused function parameters
    - usestdlibvars # Use standard library constants

  # v2: Settings moved under linters.settings
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - io.Copy
        - io.WriterTo.WriteTo
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteByte
        - (*bytes.Buffer).WriteString
        - (*strings.Builder).Write
        - (*strings.Builder).WriteByte
        - (*strings.Builder).WriteString

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam      # Allow passing large structs by value
        - rangeValCopy   # Allow range value copy for clarity
        - appendCombine  # Allow separate appends for readability
        - ifElseChain    # Allow if-else chains when clearer
        - assignOp       # Allow explicit assignment for clarity

    fatcontext:
      # Check for potential fat contexts in struct pointers
      check-struct-pointers: false  # Too many false positives

    gosec:
      excludes:
        - G104  # Audit errors not checked (handled by errcheck)
        - G115  # Integer overflow conversion (false positives)
        - G304  # File path from variable (paths are validated)
        - G401  # Weak crypto (only used for jitter, not cryptographic)

    perfsprint:
      # Optimize fmt.Sprintf into faster alternatives
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false  # Keep string concatenation readable

    sloglint:
      # Ensure consistent usage of log/slog (via custom logger wrapper)
      # Note: Many false positives due to custom logger wrapper
      # Context methods are available but not required everywhere
      context: ""       # Don't require context (too strict for wrapper)
      no-global: ""     # Allow global logger usage
      kv-only: false    # Allow both key-value and attribute styles
      attr-only: false  # Allow both styles
      no-mixed-args: true  # But ensure consistency within calls

    spancheck:
      # Checks for mistakes with OpenTelemetry spans
      checks:
        - end
        - record-error
        - set-status
      ignore-check-signatures:
        - "telemetry.RecordError"

    nilnil:
      # Allow nil,nil returns for cache miss scenarios (not found vs error)
      checked-types:
        - ptr
        - func

    misspell:
      locale: US

    revive:
      severity: warning
      confidence: 0.8
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code

    staticcheck:
      checks: ["all"]

  # v2: exclusions moved under linters.exclusions
  exclusions:
    # v2: Use 'generated' instead of 'exclude-generated'
    generated: lax
    rules:
      # Ignore certain linters in test files
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - gocritic
          - errorlint
          - intrange
      # Ignore long lines in generated files
      - path: ".*_generated\\.go"
        linters:
          - lll
      # Scraper client: caller is responsible for closing response body
      - path: internal/scraper/client\.go
        linters:
          - bodyclose
      # Allow nil,nil returns for cache miss and feature disabled scenarios
      - path: internal/storage/repository\.go
        linters:
          - nilnil
      - path: internal/genai/(expander|intent)\.go
        linters:
          - nilnil
    # v2: Use paths instead of skip-dirs
    paths:
      - third_party
      - examples

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  show-stats: true
  formats:
    text:
      path: stdout
