# https://taskfile.dev

version: '3'

vars:
  COVERAGE_FILE: coverage.out

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all
    silent: true

  # Development
  dev:
    desc: Run server in development mode
    cmds:
      - go run ./cmd/server

  warmup:
    desc: Run data warmup tool
    cmds:
      - go run ./cmd/warmup -modules=id,contact,course

  # Testing
  test:
    desc: Run all tests with coverage
    cmds:
      - go test -v -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...

  test:coverage:
    desc: Generate HTML coverage report
    deps: [test]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - cmd: Write-Host "Coverage report -> coverage.html"
        platforms: [windows]
      - cmd: echo "Coverage report -> coverage.html"
        platforms: [linux, darwin]

  # Code Quality
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout=5m ./...

  fmt:
    desc: Format all Go code
    cmds:
      - gofmt -w .

  # Docker Compose
  compose:up:
    desc: Start all services
    dir: docker
    cmds:
      - docker compose up -d

  compose:down:
    desc: Stop all services
    dir: docker
    cmds:
      - docker compose down

  compose:logs:
    desc: Show logs
    dir: docker
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  compose:restart:
    desc: Restart service
    dir: docker
    cmds:
      - docker compose restart {{.CLI_ARGS}}

  # Utilities
  clean:
    desc: Remove build artifacts and cache
    cmds:
      - cmd: Remove-Item -Recurse -Force bin, {{.COVERAGE_FILE}}, *.db -ErrorAction SilentlyContinue
        platforms: [windows]
      - cmd: rm -rf bin {{.COVERAGE_FILE}} *.db
        platforms: [linux, darwin]
      - go clean -cache -testcache

  # CI Pipeline
  ci:
    desc: Run full CI pipeline (fmt + lint + test)
    cmds:
      - go mod verify
      - task: fmt
      - task: lint
      - task: test
