# https://taskfile.dev

version: '3'

vars:
  COVERAGE_FILE: coverage.out

env:
  CGO_ENABLED: 0

tasks:
  # Development
  dev:
    desc: Run server in development mode
    env:
      LOG_LEVEL: debug
    cmds:
      - go run ./cmd/server

  # Testing
  test:
    desc: Run all tests (skipping network tests for faster CI)
    cmds:
      - go test -short -v ./...

  test:full:
    desc: Run all tests including network tests (slower, for manual testing)
    cmds:
      - go test -v ./...

  test:race:
    desc: Run tests with race detector, skipping network tests (requires CGO_ENABLED=1 on Windows)
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -short -v -race ./...

  test:coverage:
    desc: Generate HTML coverage report (skipping network tests)
    cmds:
      - go test -short -v -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report -> coverage.html"

  test:coverage:race:
    desc: Generate HTML coverage report with race detector (requires CGO_ENABLED=1 on Windows)
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -short -v -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report with race detector -> coverage.html"

  # Code Quality
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout=5m ./...

  fmt:
    desc: Format and organize imports
    cmds:
      - go run golang.org/x/tools/cmd/goimports@latest -w .

  # Build
  build:
    desc: Build all binaries
    cmds:
      - go build -o bin/ ./cmd/...

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: if exist bin rd /s /q bin
        platforms: [windows]
      - cmd: if exist coverage.out del coverage.out
        platforms: [windows]
      - cmd: if exist coverage.html del coverage.html
        platforms: [windows]
      - cmd: rm -rf bin/ coverage.out coverage.html
        platforms: [linux, darwin]

  mod:
    desc: Tidy and verify dependencies
    cmds:
      - go mod tidy
      - go mod verify

  vuln:
    desc: Run vulnerability check
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  # Docker Compose
  compose:up:
    desc: Start all services (background)
    dir: deployments
    cmds:
      - docker compose up -d

  compose:down:
    desc: Stop all services
    dir: deployments
    cmds:
      - docker compose down

  compose:logs:
    desc: "View service logs (usage: task compose:logs -- SERVICE_NAME)"
    dir: deployments
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  compose:update:
    desc: Update and restart all services with latest images
    dir: deployments
    cmds:
      - cmd: .\update.cmd
        platforms: [windows]
      - cmd: ./update.sh
        platforms: [linux, darwin]

  # Monitoring Access
  access:up:
    desc: Open monitoring dashboard access (Grafana:3000, Prometheus:9090, Alertmanager:9093)
    dir: deployments
    cmds:
      - cmd: .\access.cmd up
        platforms: [windows]
      - cmd: ./access.sh up
        platforms: [linux, darwin]

  access:down:
    desc: Close monitoring dashboard access
    dir: deployments
    cmds:
      - cmd: .\access.cmd down
        platforms: [windows]
      - cmd: ./access.sh down
        platforms: [linux, darwin]

  # CI Pipeline
  ci:
    desc: Run full CI pipeline (fmt + lint + test + build)
    cmds:
      - go mod verify
      - task: fmt
      - task: lint
      - task: test
      - task: build
