# https://taskfile.dev

version: '3'

vars:
  COVERAGE_FILE: coverage.out

env:
  CGO_ENABLED: 0

tasks:
  # Development
  dev:
    desc: Run server in development mode
    cmds:
      - go run ./cmd/server

  warmup:
    desc: Manual cache warmup (optional, server runs this automatically)
    cmds:
      - go run ./cmd/warmup

  # Testing
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:race:
    desc: Run all tests with race detector (requires CGO_ENABLED=1 on Windows)
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -v -race ./...

  test:coverage:
    desc: Generate HTML coverage report
    cmds:
      - go test -v -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report -> coverage.html"

  test:coverage:race:
    desc: Generate HTML coverage report with race detector (requires CGO_ENABLED=1 on Windows)
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -v -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report with race detector -> coverage.html"

  # Code Quality
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout=5m ./...

  fmt:
    desc: Format all Go code
    cmds:
      - gofmt -w .

  # Docker Compose
  compose:up:
    desc: Start all services (background)
    dir: deployments
    cmds:
      - docker compose up -d

  compose:down:
    desc: Stop all services
    dir: deployments
    cmds:
      - docker compose down

  compose:logs:
    desc: "View service logs (usage: task compose:logs -- SERVICE_NAME)"
    dir: deployments
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  compose:update:
    desc: Update and restart all services with latest images
    dir: deployments
    cmds:
      - cmd: .\update.cmd
        platforms: [windows]
      - cmd: ./update.sh
        platforms: [linux, darwin]

  # Monitoring Access
  access:up:
    desc: Open monitoring dashboard access (Grafana:3000, Prometheus:9090, Alertmanager:9093)
    dir: deployments
    cmds:
      - cmd: .\access.cmd up
        platforms: [windows]
      - cmd: ./access.sh up
        platforms: [linux, darwin]

  access:down:
    desc: Close monitoring dashboard access
    dir: deployments
    cmds:
      - cmd: .\access.cmd down
        platforms: [windows]
      - cmd: ./access.sh down
        platforms: [linux, darwin]

  # CI Pipeline
  ci:
    desc: Run full CI pipeline (fmt + lint + test + build)
    cmds:
      - go mod verify
      - task: fmt
      - task: lint
      - task: test
      - go build -o bin/ ./cmd/...
